//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulperia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HistoricoVentas
    {
        public int Id { get; set; }
        public int IdComprador { get; set; }
        public int IdProducto { get; set; }
        public int Cantidad { get; set; }
        public decimal Precio { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMMM/yyyy}")]
        public System.DateTime FechaCompra { get; set; }
        public string NombreComprador { get; set; }
        public string NombreProducto { get; set; }
        public decimal PrecioOriginalProducto { get; set; }
        public int Mes { get; set; }
        public int Anno { get; set; }
    }
}
