//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pulperia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PulperiaEntities : DbContext
    {
        public PulperiaEntities()
            : base("name=PulperiaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Compradores> Compradores { get; set; }
        public virtual DbSet<ComprasInventario> ComprasInventario { get; set; }
        public virtual DbSet<HistoricoComprasInventario> HistoricoComprasInventario { get; set; }
        public virtual DbSet<HistoricoVentas> HistoricoVentas { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    
        public virtual int SP_CierreMensual()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CierreMensual");
        }
    
        public virtual int SP_AjusteInventario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_AjusteInventario");
        }
    }
}
